import { describe, expect, it } from "vitest";
import {
  IdentityError,
  deobfuscate,
  exportTomcrypt,
  formatHubIdentity,
  formatTs3Identity,
  importTomcrypt,
  obfuscate,
  parseHubIdentity,
  parseIdentityString,
  parseTs3Identity,
} from "./formats";
import { base64ToBytes, publicKeyBase64, securityLevel, uidFromPublicKey } from "./keys";

/** Generated by the hub's own library (`generateIdentity(8)`), so the hub agrees on all of it. */
const HUB = {
  key: "/jdaL4Lfto9n2WMQXIYqcpY98lqOYeNWaoi/j9oiIZI=:126",
  pub: "ME0DAgcAAgEgAiEA19SppVfS/LYHw/LgEtB1jR03g2oUl0EIzMXE+3CbGiUCIQDT3XwtvXIUvnS3FCFtIfgyLrDt/OY+NTpxHoee+I62lQ==",
  uid: "qZvKeySVtV2Jln2B0EUjvQIz9kg=",
  level: 8,
};

/** tsclientlib's test key (tomcrypt, full form) and the UID it asserts. */
const TOMCRYPT_FULL =
  "MG0DAgeAAgEgAiAIXJBlj1hQbaH0Eq0DuLlCmH8bl+veTAO2+k9EQjEYSgIgNnImcmKo7ls5mExb6skfK2Tw+u54aeDr0OP1ITsC/50CIA8M5nmDBnmDM/gZ//4AAAAAAAAAAAAAAAAAAAAZRzOI";
const TOMCRYPT_FULL_UID = "lks7QL5OVMKo4pZ79cEOI5r5oEA=";
/** TS3AudioBot's short form (private scalar only), from tsclientlib's tests. */
const TOMCRYPT_SHORT = "MCkDAgbAAgEgAiBhPImh+bO1xMGOrcplwN3G74bhE9XATm+DxVo3aNtBqg==";
const TOMCRYPT_SHORT_UID = "test/9PZ9vww/Bpf5vJxtJhpz80=";

function code(fn: () => unknown): string {
  try {
    fn();
  } catch (err) {
    return err instanceof IdentityError ? err.code : `other: ${String(err)}`;
  }
  return "no error";
}

describe("keys", () => {
  it("derives the same public key, UID and level as the hub library", () => {
    const key = parseHubIdentity(HUB.key);
    const pub = publicKeyBase64(key.d);
    expect(pub).toBe(HUB.pub);
    expect(uidFromPublicKey(pub)).toBe(HUB.uid);
    expect(securityLevel(pub, key.offset)).toBe(HUB.level);
  });

  it("matches TSIdentityTool's documented fingerprint", () => {
    expect(
      uidFromPublicKey(
        "MEwDAgcAAgEgAiEAvX2kANeB4c23aW/bTKK3thz9RudAUWqzqauWpOloLYsCID54CZpzepDZyzxREwf8xNTGyTnaghxQNl+CbS7nb7Kq",
      ),
    ).toBe("Er5KNEMM3ZoatAuGZHmzSj3ZbUw=");
  });
});

describe("hub format", () => {
  it("round-trips", () => {
    expect(formatHubIdentity(parseHubIdentity(HUB.key))).toBe(HUB.key);
  });

  it("left-pads a short scalar like the library does", () => {
    const key = parseHubIdentity(HUB.key);
    const short = `${btoa(String.fromCharCode(...key.d.subarray(1)))}:5`;
    // Dropping the first byte changes the key, so only the padding is checked here.
    expect(parseHubIdentity(short).d[0]).toBe(0);
  });

  it("rejects bad counters and keys", () => {
    expect(code(() => parseHubIdentity("AAAA:-1"))).toBe("badCounter");
    expect(code(() => parseHubIdentity(`${btoa("x".repeat(40))}:1`))).toBe("badKey");
    expect(code(() => parseHubIdentity(`${btoa("\0".repeat(32))}:1`))).toBe("badKey");
    expect(code(() => parseHubIdentity("!!!:1"))).toBe("badBase64");
    expect(code(() => parseHubIdentity(`${HUB.key.split(":")[0]}:${"9".repeat(21)}`))).toBe(
      "badCounter",
    );
  });
});

describe("tomcrypt DER", () => {
  it("imports the full form with the expected UID", () => {
    const d = importTomcrypt(base64ToBytes(TOMCRYPT_FULL));
    expect(uidFromPublicKey(publicKeyBase64(d))).toBe(TOMCRYPT_FULL_UID);
  });

  it("imports TS3AudioBot's short form", () => {
    const d = importTomcrypt(base64ToBytes(TOMCRYPT_SHORT));
    expect(uidFromPublicKey(publicKeyBase64(d))).toBe(TOMCRYPT_SHORT_UID);
  });

  it("exports the full form TeamSpeak writes, byte for byte", () => {
    const d = importTomcrypt(base64ToBytes(TOMCRYPT_FULL));
    expect(exportTomcrypt(d)).toBe(TOMCRYPT_FULL);
  });

  it("refuses a public-only key and a key whose halves disagree", () => {
    expect(code(() => importTomcrypt(base64ToBytes(HUB.pub)))).toBe("noPrivateKey");
    const der = base64ToBytes(TOMCRYPT_FULL).slice();
    der[12] ^= 1; // inside x
    expect(code(() => importTomcrypt(der))).toBe("keyMismatch");
    expect(code(() => importTomcrypt(Uint8Array.of(0x30, 0x05, 1)))).toBe("badKey");
  });
});

describe("TeamSpeak 3 obfuscation", () => {
  it("round-trips arbitrary text, including a NUL-producing XOR", () => {
    for (const s of [TOMCRYPT_FULL, "b".repeat(30), "short string that is > 20"]) {
      expect(deobfuscate(obfuscate(s))).toBe(s);
    }
  });

  it("round-trips a whole identity and keeps the counter", () => {
    const key = parseHubIdentity(HUB.key);
    const ts3 = formatTs3Identity(key);
    expect(ts3.startsWith("126V")).toBe(true);
    const back = parseTs3Identity(ts3);
    expect(formatHubIdentity(back)).toBe(HUB.key);
  });

  it("is what TSIdentityTool produces (obfuscated tomcrypt of the key)", () => {
    const key = parseHubIdentity(HUB.key);
    const ts3 = formatTs3Identity(key);
    const inner = ts3.slice(ts3.indexOf("V") + 1);
    expect(deobfuscate(inner)).toBe(exportTomcrypt(key.d));
  });

  it("reports damaged strings clearly", () => {
    expect(code(() => parseTs3Identity("12Va"))).toBe("badBase64");
    expect(code(() => parseTs3Identity(`1V${btoa("x".repeat(10))}`))).toBe("badKey");
    expect(code(() => parseTs3Identity(`1V${btoa("x".repeat(64))}`))).toBe("badBase64");
  });
});

describe("parseIdentityString", () => {
  const key = parseHubIdentity(HUB.key);

  it("accepts every format, with or without quotes", () => {
    const ts3 = formatTs3Identity(key);
    for (const input of [HUB.key, ts3, `"${ts3}"`, `  ${ts3}\n`]) {
      expect(formatHubIdentity(parseIdentityString(input))).toBe(HUB.key);
    }
    expect(parseIdentityString(TOMCRYPT_SHORT).offset).toBe(0n);
  });

  it("names the problem for junk", () => {
    expect(code(() => parseIdentityString("   "))).toBe("empty");
    expect(code(() => parseIdentityString("hello world"))).toBe("unrecognized");
  });
});
